### PR TITLE
Update license year

### PR DESCRIPTION
**Pull request by m1guelpf**
TO DO:

- [x] Wait to the next year (100% done, depends on timezone)
- [ ] Merge!

:octocat:

### CODE REVIEW

**Comment by tipsy** [comment]
Thanks @m1guelpf, but I don't think licenses should be updated yearly (?)

**Comment by ploctaux** [comment]
@m1guelpf  i think you just need to add the new year and keep the old one, like 2017-2018

@tipsy well you still old the copyright in 2018 right ?

**Comment by m1guelpf** [comment]
@ploctaux Updated!

**Comment by tipsy** [comment]
I guess it can't hurt.

**Pull request merged**
