### PR TITLE
Added Dockerfile for running locally with docker + updated readme

### PR DESCRIPTION
**Pull request by bartw**
Hello,

I don't have Maven or Java installed on my machine so I added a Dockerfile to be able to run it locally.
I also included the steps to make it work in the readme.

The Dockerfile now also has support for a token using environment variables.

### CODE REVIEW

**Comment by tipsy** [comment]
Thanks @bartw, could you please update?

**Comment by alecharp** [comment]
@bartw could you reduce the size to the image. Maybe you could use multi-stage syntax to build the jar, then use a `openjdk:8-jre-alpine` image to run it.

```
FROM maven:3.5.2-jdk-8-alpine as maven-build
ENV TOKEN=""
WORKDIR /app
COPY . .
RUN mvn verify

FROM openjdk:8-jre-alpine
WORKDIR /app
COPY --from maven-build target/github-profile-summary-1.0-jar-with-dependencies.jar github-profile-summary.jar
CMD java -Doauth-token=$TOKEN -jar target/github-profile-summary.jar
```

You could even simplify the Jar name by changing the `<build><finalName>${project.artifactId}</finalName></build>` in the `pom.xml` so you won't have `1.0-jar-with...` in the copy (which will change after each release.

One side note, I'm not a huge fan (so this is entirely subjective) to run the code as root in the docker container. Wouldn't it be a good idea to create a user and make sure you run all commands with this user?

If you're not confortable with those changes (as not a maven user), @tipsy I can offer a PR to provide those changes once this PR is merged.

**Comment by tipsy** [comment]
@alecharp Feel free to create a new Docker PR (this is the second one after all). I'm not an expert on docker, so I would hoping the community would help decide which PR is better.

**Comment by bartw** [comment]
@tipsy I made changes to allow the multiple tokens and fixed the conflicts.

@alecharp I think your propositions are all very good. You can make the changes in your own PR, otherwise I would just be copying your code and you deserve the credit.

**Comment by alecharp** [comment]
@bartw I have no problem with you commiting my code, I wouldn't have noted in the comment otherwise ;) or @tipsy you can simply merge this PR as it is and I can do a PR to change the `Dockerfile`

**Comment by tipsy** [comment]
@bartw thanks, merged. Go ahead @alecharp.

**Pull request merged**
