### PR TITLE
Fetch any GitHub profile locally

### PR DESCRIPTION
**Pull request by ritiek**
This is a nice tool, thanks for writing this. I extended it to fetch for any GitHub profile when running locally using `-Dno-restriction=true`.

### CODE REVIEW

**Comment by tipsy** [comment]
I don't think `hasStarredRepo` should know about this config. It should rather be something like 

```kotlin
when (unrestricted || UserCtrl.hasStarredRepo(user)) {
    ...
}
```

**Comment by tipsy** [comment]
Thanks!

**Comment by tipsy** [comment]
@ritiek I made some additional changes: 8484dd256835e0bcf279f016d4c2c8320cb57cf2

**Comment by ritiek** [comment]
Sorry, I should have mentioned this wasn't ready to be merged yet. I don't Kotlin much, so I was wondering if there could be a better way to check if username is not an empty string ([here](https://github.com/tipsy/github-profile-summary/commit/8484dd256835e0bcf279f016d4c2c8320cb57cf2#diff-ca47b79bdef121b834e25dbf862a894eR44)) but I am glad you cross checked everything.

Thank you for the merge! :smile:

**Comment by tipsy** [comment]
> Sorry, I should have mentioned this wasn't ready to be merged yet. 

Don't worry about it. I wanted to make some other changes and I didn't want you to have to redo this PR later, so I just merged it as it was.

**Pull request merged**
